version: '3' #Docker-compose version
services: # Lista de servicios
  flask_app: #servicio/app de flask
    build: # Lista de parámetros desde los cuales construir
      context: . #contexto
      dockerfile: Dockerfile #archivo de Dockerfile
    ports: #puerto contenedor:puerto host
      - "5005:5005"
    restart: always #en caso de error o falla
    volumes:
      - .:/first_docker_b


# BUILDEO DE CONTENEDOR
# sudo docker build --tag first_docker_b .

#CORRER EL CONTENDOR
# sudo docker run -d -p 5005:5005 first_docker_b mysql:5.7 -u root -pw root -p 3600 -e MYSQL_ROOT_PASSWORD=rootpassword -e